In [1]:
# https://medium.com/nerd-for-tech/a-complete-guide-on-numpy-for-data-science-c54f47dfef8d

In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [5]:
# convert mylist to numpy array
mylistarr = np.array(mylist)

In [6]:
mylistarr

array([1, 2, 3])

In [7]:
type(mylist)

list

In [8]:
mynestedlist = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
mynestedlist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
type(mylist)

list

In [11]:
mymatrix = np.array(mynestedlist)
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
mymatrix.shape

(3, 3)

In [13]:
# np.arange(start, end, step)
# start >> inclusive
# end >> exclusive
arrangedarr = np.arange(0,11,2)
arrangedarr

array([ 0,  2,  4,  6,  8, 10])

In [14]:
arrangedarr2 = np.arange(0,10,2)
arrangedarr2

array([0, 2, 4, 6, 8])

In [15]:
# zeros array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((4,5))+1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.ones((5,5))+1

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones(5)*2

array([2., 2., 2., 2., 2.])

In [22]:
np.ones(5)/100

array([0.01, 0.01, 0.01, 0.01, 0.01])

In [23]:
# np.linspace(start, end, amount of numbers in betwwen)
# start >> inclusive
# end >> inclusive
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [24]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [25]:
ranarr1 = np.random.rand(5)
ranarr1

array([0.31768908, 0.30383067, 0.65119546, 0.84426768, 0.19700844])

In [26]:
ranarr2 = np.random.rand(5)
ranarr2

array([0.91586988, 0.80069726, 0.57853175, 0.46822265, 0.02891683])

In [27]:
ranarr3 = np.random.rand(5)
ranarr3

array([0.37872669, 0.70711916, 0.28651193, 0.63149684, 0.06162022])

In [28]:
np.random.seed(44)
ranarr4 =np.random.rand(5)
ranarr4

array([0.83484215, 0.1047961 , 0.74464048, 0.36050084, 0.35931084])

In [29]:
np.random.seed(44)
ranarr5 = np.random.rand(5)
ranarr5

array([0.83484215, 0.1047961 , 0.74464048, 0.36050084, 0.35931084])

In [30]:
np.random.seed(44)
ranarr6 = np.random.rand(5)
ranarr6

array([0.83484215, 0.1047961 , 0.74464048, 0.36050084, 0.35931084])

In [31]:
ranarr = np.random.randint(0,50,10)

In [32]:
ranarr

array([42, 23, 22, 25,  3,  7,  3, 35, 38, 45])

In [33]:
# min value in an array
ranarr.min()

3

In [34]:
# max value in an array
ranarr.max()

45

In [35]:
ranarr

array([42, 23, 22, 25,  3,  7,  3, 35, 38, 45])

In [36]:
# index location of min & max element of an array

In [37]:
# index location of min
ranarr.argmin()

4

In [38]:
# index location of max
ranarr.argmax()

9

In [39]:
arr = np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[8]

8

In [42]:
arr[1:5]
# from index 1 >> inclusive
# to index 4 >> as 5 is exclusive

array([1, 2, 3, 4])

In [43]:
arr[0:5]
# from index 0 >> inclusive
# to index 4 >> as 5 is exclusive

array([0, 1, 2, 3, 4])

In [44]:
arr[:5]
# from the beginning of the array >> inclusive
# to index 4 >> as 5 is exclusive

array([0, 1, 2, 3, 4])

In [45]:
arr[5:]
# from the index of 5 >> inclusive
# to the end of the array

array([ 5,  6,  7,  8,  9, 10])

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
new_arr = arr + 100
new_arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [48]:
new_arr2 = arr /2
new_arr2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [49]:
new_arr3 = arr ** 2
new_arr3

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
# slice arr from 0 to 5 as 6 is exclusive
arrslice1 = arr[0:6]
arrslice1

array([0, 1, 2, 3, 4, 5])

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
# make a copy from the arr
arrcopy = arr.copy()
arrcopy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
# slice arrcopy from 0 to 5 as 6 is exclusive
arrslice2 = arrcopy[0:6]
arrslice2

array([0, 1, 2, 3, 4, 5])

In [55]:
# make all elements in the arrslice2 equal 99
arrslice2[:] = 99
arrslice2

array([99, 99, 99, 99, 99, 99])

In [56]:
arrcopy
# arrcopy is cchanged permenantly

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
arr
# original array does not affected

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
# Indexing on 2D Array

In [59]:
arr_2D = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
arr_2D.shape

(3, 3)

In [61]:
arr_2D[0]

array([ 5, 10, 15])

In [62]:
arr_2D[1]

array([20, 25, 30])

In [63]:
arr_2D[2]

array([35, 40, 45])

In [64]:
arr_2D[0][0]

5

In [65]:
arr_2D[1][1]

25

In [66]:
arr_2D[2][2]

45

In [67]:
# or

In [68]:
arr_2D[0,0]

5

In [69]:
arr_2D[1,1]

25

In [70]:
arr_2D[2,2]

45

In [71]:
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [72]:
# the 1st 2 rows
# All rows from the beginning to index 1 as 2 is exclusive
arr_2D[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [73]:
# the 1st 2 rows & the last 2 columns
arr_2D[:2, 1:]

array([[10, 15],
       [25, 30]])

In [74]:
arr = np.arange(0,10)

In [75]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [77]:
1/arr

C:\Users\ascom\anaconda3\envs\ver_env\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [78]:
arr/arr

C:\Users\ascom\anaconda3\envs\ver_env\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [79]:
np.log(arr)

C:\Users\ascom\anaconda3\envs\ver_env\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [80]:
np.sum(arr)

45

In [81]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [82]:
arr.min()

0

In [83]:
arr.max()

9

In [84]:
arr.mean()

4.5

In [85]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
arr_2d.shape

(3, 4)

In [87]:
arr_2d.sum()

78

In [88]:
# return an array of sum of column elements
# no. of coulmns is 4
# you will get array of 1*4
arr_2d.sum(axis = 0)

array([15, 18, 21, 24])

In [89]:
# return array of sum of row elements
# no of rows is 3
# you will get array of 1*3
arr_2d.sum(axis = 1)

array([10, 26, 42])